import {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilContrast,
  cilCreditCard,
  cilCursor,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilGrid,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMediaRecord,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilArrowCircleLeft,
  cilArrowCircleRight,
  cilArrowThickFromTop,
  cilArrowThickToBottom,
  cilAudioSpectrum,
  cilBan,
  cilBriefcase,
  cilBrush,
  cilBullhorn,
  cilCalendarCheck,
  cilCamera,
  cilChartLine,
  cilCloud,
  cilClipboard,
  cilCursorMove,
  cilExitToApp,
  cilFolderOpen,
  cilGraph,
  cilHighlighter,
  cilKeyboard,
  cilLineWeight,
  cilLink,
  cilLockUnlocked,
  cilMobile,
  cilMonitor,
  cilMouse,
  cilMusicNote,
  cilNewspaper,
  cilNoteAdd,
  cilPaint,
  cilPaw,
  cilPowerStandby,
  cilReload,
  cilResizeBoth,
  cilRss,
  cilScreenDesktop,
  cilSend,
  cilSitemap,
  cilSmile,
  cilSnowflake,
  cilSortAscending,
  cilSortDescending,
  cilStorage,
  cilTerminal,
  cilThumbUp,
  cilVector,
  cilVideo,
  cilVolumeHigh,
  cilClock,
  cilMedicalCross,
  cilWarning
} from '@coreui/icons';

import { signet } from './signet';
import { logo } from './logo';

export const iconSubset = {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilContrast,
  cilCreditCard,
  cilCursor,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilGrid,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMediaRecord,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilArrowCircleLeft,
  cilArrowCircleRight,
  cilArrowThickFromTop,
  cilArrowThickToBottom,
  cilAudioSpectrum,
  cilBan,
  cilBriefcase,
  cilBrush,
  cilBullhorn,
  cilCalendarCheck,
  cilCamera,
  cilChartLine,
  cilCloud,
  cilClipboard,
  cilCursorMove,
  cilExitToApp,
  cilFolderOpen,
  cilGraph,
  cilHighlighter,
  cilKeyboard,
  cilLineWeight,
  cilLink,
  cilLockUnlocked,
  cilMobile,
  cilMonitor,
  cilMouse,
  cilMusicNote,
  cilNewspaper,
  cilNoteAdd,
  cilPaint,
  cilPaw,
  cilPowerStandby,
  cilReload,
  cilResizeBoth,
  cilRss,
  cilScreenDesktop,
  cilSend,
  cilSitemap,
  cilSmile,
  cilSnowflake,
  cilSortAscending,
  cilSortDescending,
  cilStorage,
  cilTerminal,
  cilThumbUp,
  cilVector,
  cilVideo,
  cilVolumeHigh,
  cilClock,
  cilMedicalCross,
  cilWarning,
  logo,
  signet
};

export enum IconSubset {
  cibCcAmex = 'cibCcAmex',
  cibCcApplePay = 'cibCcApplePay',
  cibCcMastercard = 'cibCcMastercard',
  cibCcPaypal = 'cibCcPaypal',
  cibCcStripe = 'cibCcStripe',
  cibCcVisa = 'cibCcVisa',
  cibFacebook = 'cibFacebook',
  cibGoogle = 'cibGoogle',
  cibLinkedin = 'cibLinkedin',
  cibSkype = 'cibSkype',
  cibTwitter = 'cibTwitter',
  cifBr = 'cifBr',
  cifEs = 'cifEs',
  cifFr = 'cifFr',
  cifIn = 'cifIn',
  cifPl = 'cifPl',
  cifUs = 'cifUs',
  cilAccountLogout = 'cilAccountLogout',
  cilAlignCenter = 'cilAlignCenter',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowRight = 'cilArrowRight',
  cilArrowTop = 'cilArrowTop',
  cilBasket = 'cilBasket',
  cilBell = 'cilBell',
  cilBold = 'cilBold',
  cilBookmark = 'cilBookmark',
  cilCalculator = 'cilCalculator',
  cilCalendar = 'cilCalendar',
  cilChart = 'cilChart',
  cilChartPie = 'cilChartPie',
  cilCheck = 'cilCheck',
  cilChevronLeft = 'cilChevronLeft',
  cilChevronRight = 'cilChevronRight',
  cilCloudDownload = 'cilCloudDownload',
  cilCode = 'cilCode',
  cilCommentSquare = 'cilCommentSquare',
  cilContrast = 'cilContrast',
  cilCreditCard = 'cilCreditCard',
  cilCursor = 'cilCursor',
  cilDescription = 'cilDescription',
  cilDollar = 'cilDollar',
  cilDrop = 'cilDrop',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilFile = 'cilFile',
  cilGrid = 'cilGrid',
  cilHome = 'cilHome',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilLanguage = 'cilLanguage',
  cilLayers = 'cilLayers',
  cilList = 'cilList',
  cilListNumbered = 'cilListNumbered',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMap = 'cilMap',
  cilMediaPlay = 'cilMediaPlay',
  cilMediaRecord = 'cilMediaRecord',
  cilMenu = 'cilMenu',
  cilMoon = 'cilMoon',
  cilNotes = 'cilNotes',
  cilOptions = 'cilOptions',
  cilPaperclip = 'cilPaperclip',
  cilPaperPlane = 'cilPaperPlane',
  cilPen = 'cilPen',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPrint = 'cilPrint',
  cilPuzzle = 'cilPuzzle',
  cilReportSlash = 'cilReportSlash',
  cilSave = 'cilSave',
  cilSettings = 'cilSettings',
  cilShare = 'cilShare',
  cilShareAll = 'cilShareAll',
  cilShareBoxed = 'cilShareBoxed',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilStar = 'cilStar',
  cilSun = 'cilSun',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTrash = 'cilTrash',
  cilUnderline = 'cilUnderline',
  cilUser = 'cilUser',
  cilUserFemale = 'cilUserFemale',
  cilUserFollow = 'cilUserFollow',
  cilUserUnfollow = 'cilUserUnfollow',
  cilArrowCircleLeft = 'cilArrowCircleLeft',
  cilArrowCircleRight = 'cilArrowCircleRight',
  cilArrowThickFromTop = 'cilArrowThickFromTop',
  cilArrowThickToBottom = 'cilArrowThickToBottom',
  cilAudioSpectrum = 'cilAudioSpectrum',
  cilBan = 'cilBan',
  cilBriefcase = 'cilBriefcase',
  cilBrush = 'cilBrush',
  cilBullhorn = 'cilBullhorn',
  cilCalendarCheck = 'cilCalendarCheck',
  cilCamera = 'cilCamera',
  cilChartLine = 'cilChartLine',
  cilCloud = 'cilCloud',
  cilClipboard = 'cilClipboard',
  cilCursorMove = 'cilCursorMove',
  cilExitToApp = 'cilExitToApp',
  cilFolderOpen = 'cilFolderOpen',
  cilGraph = 'cilGraph',
  cilHighlighter = 'cilHighlighter',
  cilKeyboard = 'cilKeyboard',
  cilLineWeight = 'cilLineWeight',
  cilLink = 'cilLink',
  cilLockUnlocked = 'cilLockUnlocked',
  cilMobile = 'cilMobile',
  cilMonitor = 'cilMonitor',
  cilMouse = 'cilMouse',
  cilMusicNote = 'cilMusicNote',
  cilNewspaper = 'cilNewspaper',
  cilNoteAdd = 'cilNoteAdd',
  cilPaint = 'cilPaint',
  cilPaw = 'cilPaw',
  cilPowerStandby = 'cilPowerStandby',
  cilReload = 'cilReload',
  cilResizeBoth = 'cilResizeBoth',
  cilRss = 'cilRss',
  cilScreenDesktop = 'cilScreenDesktop',
  cilSend = 'cilSend',
  cilSitemap = 'cilSitemap',
  cilSmile = 'cilSmile',
  cilSnowflake = 'cilSnowflake',
  cilSortAscending = 'cilSortAscending',
  cilSortDescending = 'cilSortDescending',
  cilStorage = 'cilStorage',
  cilTerminal = 'cilTerminal',
  cilThumbUp = 'cilThumbUp',
  cilVector = 'cilVector',
  cilVideo = 'cilVideo',
  cilVolumeHigh = 'cilVolumeHigh',
  cilMedicalCross = 'cilMedicalCross',
  cilWarning = 'cilWarning',
  cilClock = 'cilClock',
  logo = 'logo',
  signet = 'signet'
}
